on:
  workflow_call:
    inputs:
      python-version:
        default: '3.8'
        required: false
        type: string
      script:
        required: true
        type: string
      params:
        required: true
        type: string
      insertname:
        required: true
        type: string
      tubename:
        required: true
        type: string
    secrets:
      aws_credentials_file:
        required: false
      ci_token:
        required: true
      datasender_api_key:
        required: true

jobs:
  setup_data:
    name: Setup data
    runs-on: ubuntu-latest
    steps:
      - name: Set AWS credentials
        env:
          AWS_CREDENTIALS_FILE: ${{ secrets.AWS_CREDENTIALS_FILE }}
        if: env.AWS_CREDENTIALS_FILE != null
        run: mkdir ~/.aws/ && echo "$AWS_CREDENTIALS_FILE" > ~/.aws/credentials
      - name: Checkout data generator
        uses: actions/checkout@v2
        with:
          repository: infinitytracking/qa-tools
          token: ${{ secrets.CI_TOKEN }}
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ inputs.python-version }}
      - name: Install packages
        run: pip install -r data-generation/requirements.txt
      - name: Write config file
        run: |
          export APIKEY=${{ secrets.DATASENDER_API_KEY }}
          export JSON='{"apiKey": '\"$APIKEY\"'}'
          echo $JSON > config.dev.json
          cat config.dev.json
      - name: Run script
        run: |
          mkdir output
          python data-generation/${{ inputs.script }} ${{ inputs.params }} -t ${{ inputs.insertname }} -s
      - name: Create artifact
        uses: actions/upload-artifact@v2
        with:
          name: faux-data
          path: output/*
